### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by dmoskin** [shadz3rg/address-db-converter#1]
Здравствуйте. Заинтересовала ваша библиотека, подскажите, на данный момент она работает с актуальной схемой ФИАС?
Создал import.php, прописал пути, при запуске получаю:
PHP Fatal error: Uncaught Error: Access to undeclared static property: Address\Converter::$sourcePath

Путь задан: Address\Converter::$sourcePath = __DIR__ . '/import';
Права на каталог выставил, для эксперемента: 777

**Comment by shadz3rg** [comment]
Привет, библиотека давно заброшена и переписана на Питоне, оставлена как пример.
